# Generated by Django 2.0.4 on 2018-04-23 03:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180415_2217'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotCommandEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('aliases', models.CharField(default='', max_length=100)),
                ('owner_only', models.BooleanField(default=False)),
                ('bot_owner_only', models.BooleanField(default=False)),
                ('description', models.TextField(default='')),
                ('usage', models.TextField(default='')),
                ('config_help', models.TextField(default='')),
            ],
        ),
        migrations.AlterField(
            model_name='discordadmin',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False),
        ),
        migrations.AlterField(
            model_name='discordadmin',
            name='userid',
            field=models.CharField(max_length=18, unique=True, verbose_name='User ID'),
        ),
    ]
