# Generated by Django 2.0.4 on 2018-04-23 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180423_0017'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='botcommandentry',
            options={'verbose_name': 'Bot Command Entries'},
        ),
        migrations.AddField(
            model_name='botcommandentry',
            name='allows_pm',
            field=models.BooleanField(default=True),
        ),
    ]
