# Generated by Django 2.0.4 on 2018-04-23 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20180423_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botcommandentry',
            name='entry_lang',
            field=models.CharField(default='es', max_length=5, unique=True),
        ),
    ]
