# Generated by Django 2.1.2 on 2018-10-27 18:01

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_custompage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='botcommandentry',
            options={'verbose_name': 'Bot Command Entrie'},
        ),
        migrations.AlterModelOptions(
            name='custompage',
            options={'verbose_name': 'Custom Page'},
        ),
        migrations.AlterField(
            model_name='custompage',
            name='content',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
