# Generated by Django 2.1.2 on 2018-10-27 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20181027_1801'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='botcommandentry',
            options={'verbose_name': 'Bot Command Entry', 'verbose_name_plural': 'Bot Command Entries'},
        ),
    ]
