# Generated by Django 2.1.2 on 2018-10-28 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20181028_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custompage',
            name='updated_on',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
