# Generated by Django 2.1.2 on 2018-10-28 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20181028_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custompage',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='custompage',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
