# Generated by Django 2.1.2 on 2018-10-28 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20181028_0149'),
    ]

    operations = [
        migrations.AddField(
            model_name='custompage',
            name='icon_url',
            field=models.URLField(null=True, verbose_name='Page icon URL'),
        ),
    ]
